# Generated by Django 5.2.3 on 2025-07-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0002_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contact',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
