# Generated by Django 5.2.3 on 2025-07-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0004_service_description_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='clients_satisfaits',
            field=models.PositiveIntegerField(default=0, help_text='Nombre de clients satisfaits'),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_naissance',
            field=models.DateField(blank=True, help_text='Date de naissance', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience',
            field=models.CharField(blank=True, help_text="Description de l'expérience (ex : 6 mois, 2 ans, etc.)", max_length=100, null=True),
        ),
    ]
