# Generated by Django 5.2.3 on 2025-07-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0005_profile_clients_satisfaits_profile_date_naissance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Lien vers le profil Facebook', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Lien vers le profil Instagram', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='Lien vers le profil LinkedIn', null=True),
        ),
    ]
